apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: fastapi=ArpitSinghal-DevOps/fastapi-k8s-demo
    argocd-image-updater.argoproj.io/fastapi.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ArpitSinghal-DevOps/fastapi-k8s-demo:latest
        ports:
        - containerPort: 8000
